In [106]:
import numpy as np
import heapq as hq

# Дана целочисленная прямоугольная матрица. Определить:
#    количество строк, не содержащих ни одного нулевого элемента;
#    максимальное из чисел, встречающихся в заданной матрице более одного раза

mass = [ 
[3, 5 ,6],
[0, 1, 0],
[8, 5, 2]]

np_mass = np.array(mass) #NumPy - Array

print("mass = \n", np_mass, "\n")
print("\t1) количество строк, не содержащих ни одного нулевого элемента:", np.sum(np.all(np_mass != 0, axis=1)) )
print("\t2) максимальное из чисел, встречающихся в заданной матрице более одного раза:", np.max(np_mass))

mass = 
 [[3 5 6]
 [0 1 0]
 [8 5 2]] 

	1) количество строк, не содержащих ни одного нулевого элемента: 2
	2) максимальное из чисел, встречающихся в заданной матрице более одного раза: 8
