# Лабораторная работа 3.2. Домашнее задание

### Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [11]:
import numpy as np

In [12]:
a = np.arange(2, 13, 2)
b = np.array([7, 11, 15, 18, 23, 29])
print(a)
print(b)

[ 2  4  6  8 10 12]
[ 7 11 15 18 23 29]


$2.$ Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при делении на 5.

In [13]:
loc = np.logical_and(b > 12, b % 5 == 3)
a[loc]

array([ 8, 10])

$3.$ Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14". (Подсказка: в результате должен получиться массив с True и False)

In [14]:
log1 = a % 4 == 0
log2 = b < 14
print(log1 + log2)

[ True  True False  True False  True]


### Задание №2

* Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
* Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
* Проанализируйте и прокомментируйте содержательно получившиеся результаты
* Все комментарии оформляйте строго в ячейках формата markdown
    

In [1]:
import os.path
import numpy as np
import csv

file_csv = './UNdata_Export_20220403_173018777.csv'

if os.path.isfile(file_csv):
    # Load file
    data = np.array([])
    with open(file_csv, newline='') as csvfile:
        # Данных структура
        data = {
            "CountryOrArea" : np.array([]),
            "Year" : np.array([], dtype=np.int32),
            "Commodity" : np.array([]),
            "Flow" : np.array([]),
            "TradeUSD" : np.array([]),
            "WeightKg" : np.array([]),
            "QuantityName" : np.array([]),
            "Quantitykg" : np.array([]),
        }
        
        ldata = list(csv.reader(csvfile))
        
        for line in ldata[1:500]:
            data["CountryOrArea"] = np.append(data["CountryOrArea"], line[0])
            data["Year"] = np.append(data["Year"], int(line[1]))
            data["Commodity"] = np.append(data["Commodity"], line[2])
            data["Flow"] = np.append(data["Flow"], line[3])
            data["TradeUSD"] = np.append(data["TradeUSD"], float(line[4]))
            data["WeightKg"] = np.append(data["WeightKg"], line[5])
            data["QuantityName"] = np.append(data["QuantityName"], line[6])
            data["Quantitykg"] = np.append(data["Quantitykg"], line[7])
            
        ldata = None
else:
    print("Not found file:", file_csv)
    
print("Общий:")
print("\tСтрана или область:")
print("\t   количесво страна:", len(np.unique(data["CountryOrArea"])))
print()

print("\tГод:")
print("\t   от:", np.min(data["Year"]), " до:", np.max(data["Year"]))
print()

print("\tТовар:") # 
print("\t   \"ALL COMMODITIES\" (кол.) = ", len(data["Commodity"]))
print()

print("\tПоток:", np.unique(data["Flow"]))
print()

print("\tТорговля (долл. США):")
print("\t   сумма:", np.sum(data["TradeUSD"]), "кг.")
print("\t   минимальный:", "%.2f" % np.min(data["TradeUSD"]), "кг.")
print("\t   максимальный:", "%.2f" % np.max(data["TradeUSD"]), "кг.")
print("\t   cреднее арифметическое значений:", "%.2f" % np.mean(data["TradeUSD"]), "кг.")
print("\t   cтандартное отклонение:", np.std(data["TradeUSD"]), "кг.")
print("\t   дисперсия значений:", "%.2f" % np.var(data["TradeUSD"]), "кг.")
print()

print("\tВес (кг): 0")
print()

print("\tНазвание количества:")
print("\t   \"No Quantity (кол.)\" =", len(data["QuantityName"]))
print()
 
print("\tКоличество (кг): 0")    

Общий:
	Страна или область:
	   количесво страна: 11

	Год:
	   от: 1992  до: 2019

	Товар:
	   "ALL COMMODITIES" (кол.) =  499

	Поток: ['Export' 'Import' 'Re-Export' 'Re-Import']

	Торговля (долл. США):
	   сумма: 10524679880320.248 кг.
	   минимальный: 392.00 кг.
	   максимальный: 269423385464.00 кг.
	   cреднее арифметическое значений: 21091542846.33 кг.
	   cтандартное отклонение: 48600048470.16132 кг.
	   дисперсия значений: 2361964711302029901824.00 кг.

	Вес (кг): 0

	Название количества:
	   "No Quantity (кол.)" = 499

	Количество (кг): 0
